### ISSUE TITLE
selectOperation instead of selectStatus

### ISSUE THREAD

**Issue by sir-marc** [StuckiSimon/rejuice#1]
https://github.com/StuckiSimon/rejuice/blob/f85c1f602f6871ecbc5139f9a107b1b2de52fb5d/src/selector/index.js#L22-L23

Shouldn't those lines call `selectOperation` instead of `selectStatus`?
In my understanding `create` and `delete` are operations and status includes `failure`, `success` etc.

I could  create a PR if you like.

**Comment by StuckiSimon** [comment]
Agree, it's not intuitive.

But operation is a property of status and the `isDelete` / `isCreate` check for the `operation` property of the given object. https://github.com/StuckiSimon/rejuice/blob/f85c1f602f6871ecbc5139f9a107b1b2de52fb5d/src/base/index.js#L46

So it's **working as expected**.

**Please note that this is a wip and especially selectors will change drastically.**
Check out [reselect](https://github.com/reduxjs/reselect), this will be the way to go with selectors (and therefore changing how selectors work)

_If you still want to improve the code quality I'd appreciate a PR with the corresponding tests_

**Comment by StuckiSimon** [comment]
Feel free to reopen the issue if you plan to provide a PR.
